# Generated by Django 3.2.12 on 2022-05-25 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='должность')),
                ('priority', models.IntegerField(default=1000, verbose_name='приоритет')),
            ],
            options={
                'verbose_name': 'Тип должности',
                'verbose_name_plural': 'Типы должностей',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lname', models.CharField(max_length=100, verbose_name='фамилия')),
                ('fname', models.CharField(max_length=100, verbose_name='имя')),
                ('sname', models.CharField(blank=True, max_length=100, null=True, verbose_name='отчество')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='staff.posttype', verbose_name='должность')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='должность')),
                ('post_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='staff.posttype', verbose_name='тип должности')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
            },
        ),
    ]
