# Generated by Django 3.2.12 on 2022-05-25 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_auto_20220525_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='staff.post', verbose_name='должность'),
        ),
    ]
