# Generated by Django 3.2.12 on 2022-05-25 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentNumbers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=30, verbose_name='номер')),
            ],
            options={
                'verbose_name': 'Номер подразделения',
                'verbose_name_plural': 'Номера подразделения',
            },
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=250, verbose_name='подразделение'),
        ),
        migrations.AddField(
            model_name='department',
            name='numbers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='departments.departmentnumbers', verbose_name='номера'),
        ),
    ]
