# Generated by Django 3.2.12 on 2022-05-25 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_auto_20220525_2053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='numbers',
        ),
        migrations.AddField(
            model_name='departmentnumbers',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='departments.department', verbose_name='подразделение'),
        ),
    ]
